@echo off
REM MMG POS Demo Workstation Setup (Windows)
REM Configures environment variables and initializes the monorepo

setlocal enabledelayedexpansion

echo ================================
echo MMG POS Demo Workstation Setup
echo ================================
echo.

REM Check if .env files exist
if exist "pos-api\.env" (
    if exist "mmg-app\.env" (
        echo WARNING: Environment files already exist.
        set /p reconfigure="Do you want to reconfigure? (y/n): "
        if /i not "!reconfigure!"=="y" (
            echo Skipping configuration. Using existing .env files.
            echo.
            echo Next steps:
            echo   docker-compose up --build
            echo   docker-compose exec server python seed.py
            pause
            exit /b 0
        )
    )
)

echo ===== Step 1: Flask API Configuration =====
echo.

set "APP_ENV=internal-production"
set /p APP_ENV="APP_ENV [!APP_ENV!]: " || set "APP_ENV=internal-production"

set /p JWT_SECRET_KEY="JWT_SECRET_KEY (leave blank to auto-generate): "
if "!JWT_SECRET_KEY!"=="" (
    set "JWT_SECRET_KEY=change-me-to-a-long-random-secret-generated-at-setup"
)

set "DATABASE=pos"
set /p DATABASE="DATABASE [!DATABASE!]: " || set "DATABASE=pos"

set "PORT=5100"
set /p PORT="PORT [!PORT!]: " || set "PORT=5100"

set "LOCAL_DATABASE_URL=mongodb://mongo:27017"
set /p LOCAL_DATABASE_URL="LOCAL_DATABASE_URL [!LOCAL_DATABASE_URL!]: " || set "LOCAL_DATABASE_URL=mongodb://mongo:27017"

echo.
echo Remote MongoDB (optional, for cloud sync):
set /p REMOTE_DATABASE_URL="REMOTE_DATABASE_URL [skip]: "
if "!REMOTE_DATABASE_URL!"=="" (
    set "REMOTE_DATABASE_URL=mongodb+srv://^<user^>:^<pass^>@^<host^>/^<db^>?authSource=^<db^>"
)

echo.
echo ===== Step 2: Frontend Configuration =====
echo.

set "VITE_APP_ENV=internal-production"
set /p VITE_APP_ENV="VITE_APP_ENV [!VITE_APP_ENV!]: " || set "VITE_APP_ENV=internal-production"

set "VITE_APP_VERSION=MMG POS v0.1.0"
set /p VITE_APP_VERSION="VITE_APP_VERSION [!VITE_APP_VERSION!]: " || set "VITE_APP_VERSION=MMG POS v0.1.0"

set "VITE_APP_SERVER_PORT=8002"
set /p VITE_APP_SERVER_PORT="VITE_APP_SERVER_PORT [!VITE_APP_SERVER_PORT!]: " || set "VITE_APP_SERVER_PORT=8002"

set "VITE_APP_BASE_NAME=/"
set /p VITE_APP_BASE_NAME="VITE_APP_BASE_NAME [!VITE_APP_BASE_NAME!]: " || set "VITE_APP_BASE_NAME=/"

echo.
echo ===== Step 3: Creating .env files =====
echo.

REM Create pos-api/.env
(
    echo # Generated by setup-demo.bat on %date% %time%
    echo # Change these values to match your deployment environment
    echo.
    echo # -- Flask API --
    echo APP_ENV=!APP_ENV!
    echo JWT_SECRET_KEY=!JWT_SECRET_KEY!
    echo DATABASE=!DATABASE!
    echo PORT=!PORT!
    echo.
    echo # -- Database --
    echo LOCAL_DATABASE_URL=!LOCAL_DATABASE_URL!
    echo REMOTE_DATABASE_URL=!REMOTE_DATABASE_URL!
) > pos-api\.env

echo [OK] Created pos-api\.env

REM Create mmg-app/.env
(
    echo # Generated by setup-demo.bat on %date% %time%
    echo # Change these values to match your deployment environment
    echo.
    echo VITE_APP_ENV=!VITE_APP_ENV!
    echo VITE_APP_VERSION=!VITE_APP_VERSION!
    echo VITE_APP_SERVER_PORT=!VITE_APP_SERVER_PORT!
    echo VITE_APP_BASE_NAME=!VITE_APP_BASE_NAME!
) > mmg-app\.env

echo [OK] Created mmg-app\.env

echo.
echo ===== Setup complete! =====
echo.
echo Your configuration:
echo   App Environment: !APP_ENV!
echo   Database: !DATABASE!
echo   API Port: !PORT!
echo   Frontend Env: !VITE_APP_ENV!
echo.
echo Next steps:
echo.
echo 1. Review the .env files:
echo    type pos-api\.env
echo    type mmg-app\.env
echo.
echo 2. Start the stack:
echo    docker-compose up --build
echo.
echo 3. In a new terminal, seed the database (first-time only):
echo    docker-compose exec server python seed.py
echo.
echo 4. Open the app in your browser:
echo    http://localhost:8000
echo.
echo Helper app deployment:
echo   The pos-helper-app is distributed separately to cashier workstations
echo   via install.bat (handles printer config, BIR terminal credentials, etc.)
echo.
pause
