#!/bin/bash

# MMG POS Demo Workstation Setup
# Configures environment variables and initializes the monorepo

set -e

echo "================================"
echo "MMG POS Demo Workstation Setup"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env files already exist
if [ -f "pos-api/.env" ] && [ -f "mmg-app/.env" ]; then
    echo -e "${YELLOW}⚠️  Environment files already exist.${NC}"
    read -p "Do you want to reconfigure? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping configuration. Using existing .env files."
        echo ""
        echo -e "${GREEN}✓ Setup complete!${NC}"
        echo ""
        echo "Next steps:"
        echo "  docker-compose up --build"
        echo "  docker-compose exec server python seed.py"
        exit 0
    fi
fi

echo -e "${BLUE}Step 1: Flask API Configuration${NC}"
echo ""

# Default values
DEFAULT_APP_ENV="internal-production"
DEFAULT_JWT_SECRET=$(openssl rand -base64 32)
DEFAULT_DATABASE="pos"
DEFAULT_PORT="5100"
DEFAULT_LOCAL_DB="mongodb://mongo:27017"

# Prompt for values
read -p "APP_ENV [${DEFAULT_APP_ENV}]: " APP_ENV
APP_ENV=${APP_ENV:-$DEFAULT_APP_ENV}

read -p "JWT_SECRET_KEY [generated]: " JWT_SECRET_KEY
JWT_SECRET_KEY=${JWT_SECRET_KEY:-$DEFAULT_JWT_SECRET}

read -p "DATABASE [${DEFAULT_DATABASE}]: " DATABASE
DATABASE=${DATABASE:-$DEFAULT_DATABASE}

read -p "PORT [${DEFAULT_PORT}]: " PORT
PORT=${PORT:-$DEFAULT_PORT}

read -p "LOCAL_DATABASE_URL [${DEFAULT_LOCAL_DB}]: " LOCAL_DATABASE_URL
LOCAL_DATABASE_URL=${LOCAL_DATABASE_URL:-$DEFAULT_LOCAL_DB}

echo ""
echo "Remote MongoDB (optional, for cloud sync):"
read -p "REMOTE_DATABASE_URL [skip]: " REMOTE_DATABASE_URL
if [ -z "$REMOTE_DATABASE_URL" ]; then
    REMOTE_DATABASE_URL="mongodb+srv://<user>:<pass>@<host>/<db>?authSource=<db>"
fi

echo ""
echo -e "${BLUE}Step 2: Frontend Configuration${NC}"
echo ""

DEFAULT_VITE_APP_ENV="internal-production"
DEFAULT_VITE_VERSION="MMG POS v0.1.0"
DEFAULT_VITE_PORT="8002"
DEFAULT_VITE_BASE_NAME="/"

read -p "VITE_APP_ENV [${DEFAULT_VITE_APP_ENV}]: " VITE_APP_ENV
VITE_APP_ENV=${VITE_APP_ENV:-$DEFAULT_VITE_APP_ENV}

read -p "VITE_APP_VERSION [${DEFAULT_VITE_VERSION}]: " VITE_APP_VERSION
VITE_APP_VERSION=${VITE_APP_VERSION:-$DEFAULT_VITE_VERSION}

read -p "VITE_APP_SERVER_PORT [${DEFAULT_VITE_PORT}]: " VITE_APP_SERVER_PORT
VITE_APP_SERVER_PORT=${VITE_APP_SERVER_PORT:-$DEFAULT_VITE_PORT}

read -p "VITE_APP_BASE_NAME [${DEFAULT_VITE_BASE_NAME}]: " VITE_APP_BASE_NAME
VITE_APP_BASE_NAME=${VITE_APP_BASE_NAME:-$DEFAULT_VITE_BASE_NAME}

echo ""
echo -e "${BLUE}Step 3: Creating .env files${NC}"
echo ""

# Create pos-api/.env
cat > pos-api/.env << EOF
# Generated by setup-demo.sh on $(date)
# Change these values to match your deployment environment

# ── Flask API ──────────────────────────────────────────────────────────────────
APP_ENV=${APP_ENV}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
DATABASE=${DATABASE}
PORT=${PORT}

# ── Database ───────────────────────────────────────────────────────────────────
LOCAL_DATABASE_URL=${LOCAL_DATABASE_URL}
REMOTE_DATABASE_URL=${REMOTE_DATABASE_URL}
EOF

echo -e "${GREEN}✓ Created pos-api/.env${NC}"

# Create mmg-app/.env
cat > mmg-app/.env << EOF
# Generated by setup-demo.sh on $(date)
# Change these values to match your deployment environment

VITE_APP_ENV=${VITE_APP_ENV}
VITE_APP_VERSION=${VITE_APP_VERSION}
VITE_APP_SERVER_PORT=${VITE_APP_SERVER_PORT}
VITE_APP_BASE_NAME=${VITE_APP_BASE_NAME}
EOF

echo -e "${GREEN}✓ Created mmg-app/.env${NC}"

echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "Your configuration:"
echo "  App Environment: ${APP_ENV}"
echo "  Database: ${DATABASE}"
echo "  API Port: ${PORT}"
echo "  Frontend Env: ${VITE_APP_ENV}"
echo ""
echo "Next steps:"
echo ""
echo "1. Review the .env files:"
echo "   cat pos-api/.env"
echo "   cat mmg-app/.env"
echo ""
echo "2. Start the stack:"
echo "   docker-compose up --build"
echo ""
echo "3. In a new terminal, seed the database (first-time only):"
echo "   docker-compose exec server python seed.py"
echo ""
echo "4. Open the app in your browser:"
echo "   http://localhost:8000"
echo ""
echo "Helper app deployment:"
echo "  The pos-helper-app is distributed separately to cashier workstations"
echo "  via install.bat (handles printer config, BIR terminal credentials, etc.)"
echo ""
