# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'escpos',
        'escpos.printer',
        'escpos.exceptions',
        'escpos.capabilities',
        'escpos.tabulate',
        'escpos.image',
        'websockets',
        'websockets.asyncio',
        'websockets.asyncio.server',
        'websockets.legacy',
        'websockets.legacy.server',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'pydash',
        'pytz',
        'PIL',
        'PIL.Image',
        'qrcode',
        'qrcode.image.base',
        'qrcode.image.pure',
        'barcode',
        'barcode.writer',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='mmg-helper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
