#!/usr/bin/env bash
# Sets up a NEW branch POS server (the Docker half of a POS station): writes pos-api/.env,
# builds and starts the stack, seeds it from central, and verifies it tallies with central.
# Cashier PCs are set up separately with the helper installer — see README.md, "Setting Up a
# New Branch POS Station", Part B.
#
# Usage (from the repo root):  ./scripts/setup-pos-station.sh
# Optional env overrides:      REMOTE_DATABASE_URL=mongodb://... JWT_SECRET_KEY=... ./scripts/setup-pos-station.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

step() { printf '\n==> %s\n' "$1"; }
fail() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
step "Checking prerequisites"
command -v docker >/dev/null 2>&1 || fail "Docker is not installed (https://www.docker.com/products/docker-desktop)."
docker info >/dev/null 2>&1 || fail "Docker is installed but not running — start Docker and re-run."
if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  fail "Neither 'docker compose' nor 'docker-compose' is available."
fi
echo "Using: $DC"

# ── 2. pos-api/.env ──────────────────────────────────────────────────────────
step "Configuring pos-api/.env"
WRITE_ENV=1
if [ -f pos-api/.env ]; then
  read -r -p "pos-api/.env already exists. Keep it? [Y/n] " keep
  if [[ ! "${keep:-Y}" =~ ^[Nn]$ ]]; then WRITE_ENV=0; fi
fi

if [ "$WRITE_ENV" = 1 ]; then
  if [ -z "${REMOTE_DATABASE_URL:-}" ]; then
    echo "A branch server copies its users/branches/products from central, so it needs the"
    echo "central MongoDB URL (ask whoever runs the central/UAT server)."
    read -r -p "REMOTE_DATABASE_URL (central MongoDB): " REMOTE_DATABASE_URL
  fi
  [ -n "${REMOTE_DATABASE_URL:-}" ] || fail "REMOTE_DATABASE_URL is required — seeding refuses to invent its own lookup ids (see pos-api/SEEDING.md)."

  if [ -z "${JWT_SECRET_KEY:-}" ]; then
    if command -v openssl >/dev/null 2>&1; then JWT_SECRET_KEY="$(openssl rand -hex 32)"
    else JWT_SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"; fi
  fi

  cat > pos-api/.env <<EOF
# Generated by scripts/setup-pos-station.sh on $(date)
APP_ENV=internal-production
JWT_SECRET_KEY=${JWT_SECRET_KEY}
DATABASE=pos
PORT=5100
LOCAL_DATABASE_URL=mongodb://mongo:27017
REMOTE_DATABASE_URL=${REMOTE_DATABASE_URL}
EOF
  echo "Wrote pos-api/.env"
else
  echo "Keeping existing pos-api/.env"
fi

# ── 3. Build and start ───────────────────────────────────────────────────────
step "Building and starting the stack (first build takes a few minutes)"
$DC up --build -d

# ── 4. Wait for the API ──────────────────────────────────────────────────────
step "Waiting for the API on :8001"
ready=0
for _ in $(seq 1 60); do
  code="$(curl -s -o /dev/null -w '%{http_code}' -X POST http://localhost:8001/login || true)"
  if [ "$code" != "000" ]; then ready=1; break; fi
  sleep 2
done
[ "$ready" = 1 ] || fail "API did not come up in 2 minutes. Check: $DC logs server"
echo "API is up."

# ── 5. Seed from central ─────────────────────────────────────────────────────
step "Seeding the database (should print 'Bootstrapping lookup data from central')"
if ! $DC exec -T server python seed.py; then
  fail "Seeding failed. On a branch it must reach central — check REMOTE_DATABASE_URL in pos-api/.env and that this machine can reach it, then re-run."
fi

# ── 6. Verify against central ────────────────────────────────────────────────
step "Verifying lookup data tallies with central (should end with TALLY OK)"
if ! $DC exec -T sync python reconcile.py --verify; then
  echo "WARNING: tally check did not pass — see pos-api/SEEDING.md, 'Repairing a database that was seeded the old way'." >&2
fi

# ── 7. Done ──────────────────────────────────────────────────────────────────
LAN_IP="$( (hostname -I 2>/dev/null | awk '{print $1}') || true )"
[ -n "$LAN_IP" ] || LAN_IP="$( (ipconfig getifaddr en0 2>/dev/null) || true )"
[ -n "$LAN_IP" ] || LAN_IP="<this-machine-ip>"

cat <<EOF

Branch server is up.

  Cashier browsers open:   http://${LAN_IP}:8000
  Log in with:             an account from central (users are copied down from it)
  Ports cashier PCs must reach on this machine: 8000 (app) and 8002 (API proxy)

Next: install the helper on each cashier PC (README.md, Part B). Do NOT create test
transactions on this stack — sync is running and pushes real data to central.
EOF
